version: "INDEV-1.2.0" # PLEASE DON'T EDIT THIS LINE! OTHERWISE, ERRORS AND DATA LOSS MAY OCCUR!

messageColors:
  default: "white"
  success: "green"
  error: "red"
  info: "blue"
  clickable: "gold"
  overworld: "dark_green"
  nether: "dark_red"

onPlayerJoinMessage: "Hi du Lauch!"
printDeathCordsPublic: true